const songs = [
  { title: '1da Banton Ft Kizz Daniel Tiwa Savage - No Wahala Remix (Copy)', audio: './1da_Banton_Ft_Kizz_Daniel_Tiwa_Savage_-_No_Wahala_Remix_ - Copy.mp3' },
  { title: '1da Banton Ft Kizz Daniel Tiwa Savage - No Wahala Remix', audio: './1da_Banton_Ft_Kizz_Daniel_Tiwa_Savage_-_No_Wahala_Remix_.mp3' },
  { title: 'Olamide - Cup Of Tea', audio: './08-Olamide-Cup-Of-Tea-JustNaija.com_.mp3' },
  { title: '9ice - Pete Pete Ft Asa', audio: './9-Ice-15-Pete-Pete-Feat-Asa.mp3' },
  { title: '9ice Ft Bella Shmurda - Low Key', audio: './9ice-Ft-Bella-Shmurda-Low-Key-(TrendyBeatz.com).mp3' },
  { title: 'Adekunle Gold Ft Davido - High', audio: './Adekunle_Gold_Ft_Davido_-_High.mp3' },
  { title: 'Adekunle Gold Ft Lucky Daye - Sinner', audio: './Adekunle_Gold_ft_Lucky_Daye_-_Sinner.mp3' },
  { title: 'Adekunle Gold - Omo Eko', audio: './Adekunle-Gold---Omo-Eko.mp3' },
  { title: 'Adekunle Gold Ft DJ Spinall - Cloud 9', audio: './Adekunle-Gold-Ft-DJ-Spinall-Cloud-9-(TrendyBeatz.com).mp3' },
  { title: 'Another Trip Around The Sun', audio: './Another trip around the sun .mp3' },
  { title: 'Asake - 2:30', audio: './Asake_-_2_30.mp3' },
  { title: 'Asake - Lonely At The Top', audio: './Asake_-_Lonely_At_The_Top.mp3' },
  { title: 'Asake Ft Olamide - Trabaye', audio: './Asake_Ft_Olamide_-_Trabaye.mp3' },
  { title: 'Asake - Dull', audio: './Asake-Dull-New-Song-(TrendyBeatz.com).mp3' },
  { title: 'Asake Ft Fireboy DML - Bandana', audio: './Asake-Ft-Fireboy-DML-Bandana-(TrendyBeatz.com).mp3' },
  { title: 'Asake Ft Olamide - Amapiano', audio: './Asake-Ft-Olamide-Amapiano-New-Song-(TrendyBeatz.com).mp3' },
  { title: 'Asake Ft Russ - Reason', audio: './Asake-Ft-Russ-Reason-New-Song-(TrendyBeatz.com).mp3' },
  { title: 'Asake Ft Tiwa Savage - Loaded', audio: './Asake-Ft-Tiwa-Savage-Loaded-(TrendyBeatz.com).mp3' },
  { title: 'Asake - Joha', audio: './Asake-Joha-New-Song-(TrendyBeatz.com).mp3' },
  { title: 'Asake - Nzaza', audio: './Asake-Nzaza-New-Song-(TrendyBeatz.com).mp3' },
  { title: 'Asake - Organise', audio: './Asake-Organise-New-Song-(TrendyBeatz.com).mp3' },
  { title: 'Asake - Peace Be Unto You', audio: './Asake-Peace-Be-Unto-You-PBUY.mp3' },
  { title: 'Asake - Sungba Remix Ft Burna Boy', audio: './Asake-Sungba-Remix-ft.-Burna-Boy.mp3' },
  { title: 'Asake - Terminator', audio: './Asake-Terminator-(TrendyBeatz.com).mp3' },
  { title: 'AUD 20260501 WA0008', audio: './AUD-20260501-WA0008.mp3' },
  { title: 'Ayra Starr - Bloody Samaritan', audio: './Ayra_Starr_-_Bloody_Samaritan.mp3' },
  { title: 'Ayra Starr - Stability', audio: './Ayra_starr_-_Stability_Niggaloaded.com.ng.mp3' },
  { title: 'Ayra Starr - Pele O (Drill Refix)', audio: './Ayra_Starr_Drill_Refix_by_Precious_-_Pele_o.mp3' },
  { title: 'Ayra Starr Ft CKay - Beggie Beggie', audio: './Ayra-Starr-Beggie-Beggie-ft-CKay-(TrendyBeatz.com).mp3' },
  { title: 'Ayra Starr - Rush', audio: './Ayra-Starr-Rush-Naijahits-com.mp3' },
  { title: 'Ayra Starr - Toxic', audio: './Ayra-Starr-Toxic-(TrendyBeatz.com).mp3' },
  { title: 'Backpack Bounce', audio: './Backpack Bounce (1).mp3' },
  { title: 'Bella Shmurda Ft Nasty C - Philo Remix', audio: './Bella-Shmurda-Ft-Nasty-C-Philo-Remix-New-Song-(TrendyBeatz.com).mp3' },
  { title: 'Bella Shmurda - Level Up', audio: './Bella-Shmurda-Level-Up-(TrendyBeatz.com).mp3' },
  { title: 'Berri Tiga Ft Carter Efe - Machala', audio: './Berri-Tiga-Ft-Carter-Efe-Machala-(TrendyBeatz.com).mp3' },
  { title: 'Black Sherif - Kwaku The Traveller', audio: './Black_Sherif_-_Kwaku_The_Traveller.mp3' },
  { title: 'BNXN (Buju) Ft Kizz Daniel & Seyi Vibez - Gwagalada', audio: './BNXN_Buju_Ft_Kizz_Daniel_Seyi_Vibez_-_Gwagalada.mp3' },
  { title: 'BNXN (Buju) Ft Kizz Daniel & Seyi Vibez - Gwagalada', audio: './BNXN-fka-Buju-Ft-Kizz-Daniel-and-Seyi-Vibez-Gwagwalada-(TrendyBeatz.com).mp3' },
  { title: 'BNXN Ft Minz & Blaqbonez - Wo Wo Remix', audio: './BNXN-Ft-Minz-and-Blaqbonez-Wo-Wo-Remix-(TrendyBeatz.com).mp3' },
  { title: 'Boy Spyce - Folake', audio: './Boy_Spyce_-_Folake_VistaNaija.Com.mp3' },
  { title: 'Buju Ft Pheelz - Finesse', audio: './Buju-Ft-Pheelz-Finesse-(TrendyBeatz.com).mp3' },
  { title: 'Buju Ft Pheelz - If I Broke Na My Business', audio: './Buju-Ft-Pheelz-If-I-Broke-Na-My-Business-(TrendyBeatz.com).mp3' },
  { title: 'Burna Boy - It\'s Plenty', audio: './Burna_Boy_-_It_s_Plenty_042jam.com.mp3' },
  { title: 'Burna Boy - Last Last', audio: './Burna_Boy_-_Last_Last_042jam.com.mp3' },
  { title: 'Burna Boy Ft Wizkid - Ballon D\'or', audio: './Burna_Boy_ft_Wizkid_-_Ballon_D_or.mp3' },
  { title: 'CKay - Emiliana', audio: './Ckay_-_Emiliana.mp3' },
  { title: 'CKay - Love Nwantiti', audio: './CKAY_-_LOVE_NWANTINTI.mp3' },
  { title: 'CKay Ft Joeboy & Kuami Eugene - Love Nwantiti Remix', audio: './Ckay_ft_Joeboy_Kuami_Eugene_-_Love_Nwantiti_Remix_.mp3' },
  { title: 'CKay Ft Davido, Focalistic & Abidoza - Watawi', audio: './Ckay-Ft-Davido-Focalistic-and-Abidoza-Watawi-(TrendyBeatz.com).mp3' },
  { title: 'Davido - Feel', audio: './Davido_-_Feel.mp3' },
  { title: 'Davido Ft Asake - No Competition', audio: './Davido_Ft_Asake_-_No_Competition.mp3' },
  { title: 'Davido Ft Musa Keys - Unavailable', audio: './Davido_Ft_Musa_Keys_-_Unavailable.mp3' },
  { title: 'Davido Ft Skepta - U', audio: './Davido_Ft_Skepta_-_U.mp3' },
  { title: 'Davido - Animashaun feat Yonda', audio: './Davido-Animashaun-feat-Yonda-[TrendyBeatz.com].mp3' },
  { title: 'Davido - Flora My Flawa', audio: './Davido–Flora-My-Flawa-(TrendyBeatz.com).mp3' },
  { title: 'DJ Neptune Ft Omah Lay & Joeboy - Abeg', audio: './DJ_Neptune_Ft_Omah_Lay_Joeboy_-_Abeg.mp3' },
  { title: 'DJ Spinall Ft Adekunle Gold - Cloud 9', audio: './DJ_Spinall_Ft_Adekunle_Gold_-_Cloud_9.mp3' },
  { title: 'DJ Spinall Ft Asake - Palazzo', audio: './DJ_Spinall_Ft_Asake_-_Palazzo.mp3' },
  { title: 'DJ Spinall Ft Wizkid - Loju', audio: './DJ-Spinall-Ft-Wizkid-Loju-(TrendyBeatz.com).mp3' },
  { title: 'Drake - Hotline Bling', audio: './Drake_-_Hotline_Bling_[NaijaGreen.Com]_.mp3' },
  { title: 'Fave - Beautifully', audio: './Fave-Beautifully-(TrendyBeatz.com).mp3' },
  { title: 'Fireboy DML - Someone', audio: './Fireboy_DML_-_Someone.mp3' },
  { title: 'Fireboy DML Ft Ed Sheeran - Peru Remix', audio: './Fireboy_DML_Ft_Ed_Sheeran_-_Peru_Remix_.mp3' },
  { title: 'Flavour Ft Umu Obiligbo - Odogwu', audio: './Flavour-Ft-Umu-Obiligbo-Odogwu-(TrendyBeatz.com).mp3' },
  { title: 'Flavour - Ijele feat Zoro', audio: './Flavour-Ijele-feat.Zoro-[TrendyBeatz.com].mp3' },
  { title: 'Goya Menor & Nektunez - Ameno Amapiano Remix', audio: './Goya_Menor_Nektunez_-_Ameno_Amapiano_Remix_.mp3' },
  { title: 'Imagine Dragons - America', audio: './Imagine_Dragons_-_America.mp3' },
  { title: 'Imagine Dragons - Follow You', audio: './Imagine_Dragons_-_Follow_You.mp3' },
  { title: 'Imagine Dragons - Demons (Sped Up)', audio: './Imagine-Dragons-demons-sped-up-(HiphopKit.com).mp3' },
  { title: 'Imagine Dragons - Monday', audio: './Imagine-Dragons-Monday-(HiphopKit.com).mp3' },
  { title: 'Imagine Dragons - Sharks', audio: './Imagine-Dragons-Sharks_-_Soloplay.ng.mp3' },
  { title: 'Joeboy - Alcohol', audio: './Joeboy_-_Alcohol.mp3' },
  { title: 'Joeboy - Cubana', audio: './Joeboy_-_Cubana.mp3' },
  { title: 'K1 De Ultimate - Ade Ori Okin', audio: './K1-D-Ultimate-Ade-Ori-Okin.mp3' },
  { title: 'K1 De Ultimate - Majo Nisho', audio: './K1-De-Ultimate-Majo-Nisho.mp3' },
  { title: 'Kcee - Ojapiano', audio: './Kcee_-_Ojapiano.mp3' },
  { title: 'Kizz Daniel - Eh God Barnabas', audio: './Kizz_Daniel_-_Eh_God_Barnabas_.mp3' },
  { title: 'Kizz Daniel - Pour Me Water Remix', audio: './Kizz_Daniel_-_Pour_Me_Water_Remix_.mp3' },
  { title: 'Kizz Daniel - Shu Peru', audio: './Kizz_Daniel_-_Shu-Peru.mp3' },
  { title: 'Kizz Daniel Ft Tekno - Buga', audio: './Kizz_Daniel_ft_Tekno_-_Buga.mp3' },
  { title: 'Ladipoe Ft Fireboy DML - Running', audio: './Ladipoe_ft_Fireboy_DML_-_Running.mp3' },
  { title: 'Lighthouse Family - Ocean Drive', audio: './Lighthouse_Family_-_Ocean_Drive_[NaijaGreen.Com]_.mp3' },
  { title: 'Lil Kesh Ft Naira Marley - Korope', audio: './Lil_Kesh_ft_Naira_Marley_-_Korope.mp3' },
  { title: 'Lil Nas X Ft Jack Harlow - Industry Baby', audio: './Lil-Nas-X-Ft-Jack-Harlow-Industry-Baby-(TrendyBeatz.com).mp3' },
  { title: 'Lojay Ft Sarz - Monalisa', audio: './Lojay_Ft_Sarz_-_Monlisa.mp3' },
  { title: 'Mavins - Overdose', audio: './Mavins_Crayon_Ayra_Starr_LADIPOE_Magixx_Boy_Spyce_-_Overdose.mp3' },
  { title: 'Mavins - Won Da Mo', audio: './Mavins_Ft_Rema_Ayra_Starr_LadiPoe_Crayon_Bayanni_Boy_Spyce_Magixx_Johnny_Drille_-_Won_Da_Mo.mp3' },
  { title: 'Mayorkun Ft Victony - Holy Father (1)', audio: './Mayorkun_ft_Victony_-_Holy_Father-1.mp3' },
  { title: 'Mayorkun Ft Victony - Holy Father', audio: './Mayorkun_ft_Victony_-_Holy_Father.mp3' },
  { title: 'MI Abaga - Bad Belle Ft Moti Cakes', audio: './MI-Abaga-Bad-Belle-Feat-Moti-Cakes-[TrendyBeatz.com].mp3' },
  { title: 'Mohbad - Backside', audio: './Mohbad_-_Backside_audio.mp3' },
  { title: 'Naira Marley - Kojosese', audio: './Naira_Marley_Kojosese_9jaflaver.com_.mp3' },
  { title: 'Naira Marley Ft Busiswa - Coming', audio: './Naira-marley-Coming-ft-Busiswa-Naira-marley-Coming-ft-Busiswa-(BeatzJam.com).mp3' },
  { title: 'Nathan Evans - Wellerman', audio: './Nathan_Evans_-_Wellerman.mp3' },
  { title: 'Nero Ilaya - Toto Oba', audio: './Nero Ilaya_Toto Oba.mp3' },
  { title: 'Olamide Ft Asake - Omo Ope', audio: './Olamide-Ft-Asake-Omo-Ope-(TrendyBeatz.com).mp3' },
  { title: 'Olamide - Rock', audio: './Olamide-Rock.mp3' },
  { title: 'Omah Lay - Free My Mind (Copy)', audio: './Omah_Lay_-_Free_My_Mind - Copy.mp3' },
  { title: 'Omah Lay - Free My Mind', audio: './Omah_Lay_-_Free_My_Mind.mp3' },
  { title: 'Omah Lay - Soso', audio: './Omah_Lay_-_Soso.mp3' },
  { title: 'Omah Lay - Godly', audio: './Omah-Lay-Godly-(TrendyBeatz.com).mp3' },
  { title: 'Otega - Shayo', audio: './Otega-Shayo-(TrendyBeatz.com).mp3' },
  { title: 'Pheelz Ft Davido - Electricity', audio: './Pheelz-Ft-Davido-Electricity-(TrendyBeatz.com).mp3' },
  { title: 'Poco Lee Ft Hotkid - Otilo Izz Gone', audio: './Poco_Lee_Ft_Hotkid_-_Otilo_Izz_Gone_.mp3' },
  { title: 'Poco Lee x Portable x Olamide - Zazoo Zehh', audio: './Poco_Lee_x_Portable_x_Olamide_-_Zazoo_Zehh.mp3' },
  { title: 'Reekado Banks - Ozumba Mbadiwe', audio: './Reekado-Banks-Ozumba-Mbadiwe-(TrendyBeatz.com).mp3' },
  { title: 'Rema - Alien', audio: './Rema_-_Alien.mp3' },
  { title: 'Rema - Holiday', audio: './Rema_-_Holiday_Audio_.mp3' },
  { title: 'Rema - Bounce', audio: './Rema-Bounce-Booty-Bounce-(TrendyBeatz.com).mp3' },
  { title: 'Rema - Calm Down', audio: './Rema-Calm-Down.mp3' },
  { title: 'Rema - Charm', audio: './Rema-Charm-New-Song-(TrendyBeatz.com).mp3' },
  { title: 'Rema - Dumebi', audio: './Rema-Dumebi-[TrendyBeatz.com].mp3' },
  { title: 'Rema Ft Selena Gomez - Calm Down Remix', audio: './Rema-Ft-Selena-Gomez-Calm-Down-Remix-New-Song-(TrendyBeatz.com).mp3' },
  { title: 'Rexxie Ft Skiibii & Naira Marley - Abracadabra', audio: './Rexxie-Ft-Skiibii-and-Naira-Marley-Abracadabra-(TrendyBeatz.com).mp3' },
  { title: 'Ruger - Asiwaju', audio: './Ruger_-_Asiwaju_Video_.mp3' },
  { title: 'Ruger - Bun Bun', audio: './Ruger_-_Bun_Bun.mp3' },
  { title: 'Ruger - Dior', audio: './Ruger_-_Dior.mp3' },
  { title: 'Ruger - Bounce', audio: './Ruger-Bounce-(TrendyBeatz.com).mp3' },
  { title: 'Scroll Through the Sky', audio: './Scroll Through the Sky.mp3' },
  { title: 'Second Sermon Remix Ft Burna Boy', audio: './Second-Sermon-Remix-ft.-Burna-Boy.mp3' },
  { title: 'Seyi Vibez - Chance Na Ham', audio: './Seyi_Vibez_-_Chance_Na_Ham_.mp3' },
  { title: 'Seyi Vibez - Kunfaya Kun Be And It Is', audio: './Seyi_Vibez_-_Kunfaya_Kun_Be_And_It_Is_.mp3' },
  { title: 'Seyi Vibez - Hat-trick', audio: './Seyi-Vibez---Hat-trick.mp3' },
  { title: 'Seyi Vibez - Bullion Van', audio: './Seyi-Vibez-Bullion-Van-(TrendyBeatz.com).mp3' },
  { title: 'Seyi Vibez - Para Boi', audio: './Seyi-Vibez-Para-Boi-(TrendyBeatz.com).mp3' },
  { title: 'Shaggy - Boombastic', audio: './Shaggy_-_Boombastic_[NaijaGreen.Com]_.mp3' },
  { title: 'Simi Ft Joeboy - So Bad', audio: './Simi_ft_Joeboy_-_So_Bad.mp3' },
  { title: 'Sisq Ft Beanie Siegel - Unleash The Dragon', audio: './Sisq_ft_Beanie_Siegel_-_Unleash_The_Dragon_Qoret.com.mp3' },
  { title: 'Skiibi Ft Davido - Baddest Boy Remix', audio: './Skiibi_Ft_Davido_Baddest_Boy_Remix_9jaflaver.com_.mp3' },
  { title: 'Skiibii Ft Davido - Baddest Boy Remix', audio: './Skiibii_ft_Davido_-_Baddest_Boy_Remix_.mp3' },
  { title: 'Sleazy Stereo - Spongebob Squarepants Remix', audio: './Sleazy_Stereo_-_Spongebob_Squarepants_Remix_.mp3' },
  { title: 'Take Me Back', audio: './Take_Me_Back.mp3' },
  { title: 'The Notorious B.I.G. - Notorious B.I.G.', audio: './The-Notorious-B.I.G.-Notorious-B.I.G.-via-Naijafinix.com-Copy.mp3' },
  { title: 'Timaya - Sweet Us', audio: './Timaya_-_SWEET_US.mp3' },
  { title: 'Tiwa Savage Ft Asake - Loaded', audio: './Tiwa_Savage_ft_Asake_-_Loaded.mp3' },
  { title: 'Tiwa Savage Ft Brandy - Somebody\'s Son', audio: './Tiwa_Savage_Ft_Brandy_-_Somebody_s_Son.mp3' },
  { title: 'Tiwa Savage Ft Ayra Starr & Young Jonn - Stamina', audio: './Tiwa-Savage-Ft-Ayra-Starr-and-Young-Jonn-Stamina-(TrendyBeatz.com).mp3' },
  { title: 'Tiwa Savage Ft Spyro - Who Is Your Guy Remix', audio: './Tiwa-Savage-Ft-Spyro-Who-Is-Your-Guy-Remix-(TrendyBeatz.com).mp3' },
  { title: 'Victony Ft Omah Lay - Soweto Remix', audio: './Victony_Ft_Omah_Lay_-_Soweto_Remix_.mp3' },
  { title: 'Victor AD - Billz', audio: './Victor_AD_-_Billz.mp3' },
  { title: 'Voltage Of Hype Ft DJ Dabila - Amapiano Breakfast', audio: './Voltage-Of-Hype-Ft-DJ-Dabila-Amapiano-Breakfast-(TrendyBeatz.com).mp3' },
  { title: 'Young Jonn Ft Olamide - Currency', audio: './Young-Jonn-Ft-Olamide-Currency-New-Song-(TrendyBeatz.com).mp3' },
  { title: 'Young Jonn - Xtra Cool', audio: './Young-Jonn-Xtra-Cool-(TrendyBeatz.com).mp3' },
  { title: 'Zinoleesky - Kilofeshe', audio: './Zinoleesky_-_Kilofeshe.mp3' },
  { title: 'Zinoleesky - Many Things', audio: './Zinoleesky_-_Many_Things.mp3' },
  { title: 'Zinoleesky Ft Adekunle Gold - Party No Dey Stop', audio: './Zinoleesky-Ft-Adekunle-Gold-Party-No-Dey-Stop-(TrendyBeatz.com).mp3' },
  { title: 'Zlatan Ft Asake & Peruzzi - Mr Money Remix', audio: './Zlatan-Ft-Asake-and-Peruzzi-Mr-Money-Remix-(TrendyBeatz.com).mp3' },
];
